---
title: "BCC animal data"
subtitle: "Data preps"
author: "Radoslaw Panczak"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    highlight: pygments
    # keep_md: yes
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 4
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

<!-- ------------------------------------------------------------ --> 
<!-- ------------------------------------------------------------ --> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width=8, fig.height=6, dpi=300, out.width="800px", out.height="600px")

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
set.seed(12345)
options(scipen = 999)

library(pacman) 
p_load(tidyverse, readxl, janitor, sjmisc,
       sf, rmapshaper, tmap)

tmap_mode("view") # makes map interactive

# library("tidylog")
# library("conflicted")
# for (f in getNamespaceExports("tidylog")) {
#   conflicted::conflict_prefer(f, "tidylog", quiet = TRUE)
# }
```

# Neighbourhood boundaries

## ABS

```{r eval=FALSE, include=FALSE}
SSC <- st_read("data/geo/raw/1270055003_ssc_2016_aust_shape/SSC_2016_AUST.shp", 
               stringsAsFactors = FALSE) %>% 
  mutate(SSC_CODE16 = as.integer(SSC_CODE16),
         STE_CODE16 = as.integer(STE_CODE16)) %>% 
  select(-STE_NAME16, -STE_CODE16, -AREASQKM16) %>% 
  st_transform(3112) %>% 
  filter(!st_is_empty(geometry))

# SSC <- ms_simplify(SSC, keep = 0.05, weighting = 0.7) # default settings

saveRDS(SSC, "data/geo/clean/SSC_2016_AUST.Rds")

plot(st_geometry(SSC))
# qtm(SSC)
```

```{r}
SSC <- readRDS("data/geo/clean/SSC_2016_AUST.Rds")

glimpse(SSC)
```

## QSC

```{r eval=FALSE, include=FALSE}
LB <- st_read("data/geo/raw/QSC_Extracted_Data_20190816_111155192000-13108/Locality_Boundaries.shp", 
              stringsAsFactors = FALSE) %>% 
  select(-ADMINTYPEN, -CA_AREA_SQ, -SHAPE_Leng, -SHAPE_Area) %>% 
  mutate(LOC_CODE = as.integer(LOC_CODE)) %>% 
  st_transform(3112) %>% 
  filter(!st_is_empty(geometry))

# LB <- ms_simplify(LB, keep = 0.05, weighting = 0.7) # default settings

saveRDS(LB, "data/geo/clean/Locality_Boundaries.Rds")

plot(st_geometry(SSC))
# qtm(SSC)
```

```{r}
LB <- readRDS("data/geo/clean/Locality_Boundaries.Rds")

glimpse(LB)
```

# SEIFA

```{r}
SEIFA <- read_xls("data/SEIFA/raw/2033055001 - ssc indexes.xls", 
                  sheet = "Table 1", skip = 5, n_max = 13719, na = "-") %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>% 
  select(-starts_with("score_")) %>% 
  dplyr::rename(SSC_CODE16 = x1,
                SSC_NAME16 = x2,
                IRSD = decile_4,
                IRSAD = decile_6,
                IER = decile_8,
                IEO = decile_10,
                URP = x11,
                caution = x12) %>% 
  mutate(SSC_CODE16 = as.integer(SSC_CODE16),
         IRSD = as.integer(IRSD),
         IRSAD = as.integer(IRSAD),
         IER = as.integer(IER),
         IEO = as.integer(IEO),
         URP = as.integer(URP)
  ) %>% 
  mutate(caution = as.logical(ifelse(is.na(caution), "False", "True")))

saveRDS(SEIFA, "data/SEIFA/clean/SEIFA.Rds")
```

```{r}
SEIFA <- readRDS("data/SEIFA/clean/SEIFA.Rds")

glimpse(SEIFA)

# frq(SEIFA, IRSD)
```

# Dog cost 

```{r include=FALSE}
## Source 1
dog_expensive_1 <- read_xlsx("data/costs/raw/dog_expensive.xlsx") %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>% 
  # fill(web_source)
  select(-web_source) %>% 
  filter(source == "lifestyle") %>% 
  rename(dog_breed = breed)

# View(dog_expensive_1)

## Source 2
dog_expensive_2 <- read_xlsx("data/costs/raw/dog_expensive.xlsx") %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>% 
  select(-web_source) %>% 
  filter(source == "pet insurance australia") %>% 
  rename(dog_breed = breed)

# View(dog_expensive_2)
```


```{r}
## Combined
dog_expensive <- 
  select(dog_expensive_1, dog_breed) %>% 
  bind_rows(select(dog_expensive_2, dog_breed)) %>% 
  distinct() %>% 
  arrange(dog_breed)

saveRDS(dog_expensive, "data/costs/clean/dog_expensive.Rds")

kableExtra::kable(dog_expensive)
```


# Dog insurance

```{r eval=FALSE, include=FALSE}
# packages needed
# install.packages("rvest")

library(rvest)
library(tidyverse)

# scraping table done with this using chrome: https://www.r-bloggers.com/using-rvest-to-scrape-an-html-table/
url <- 'https://top10petinsurance.com.au/pet-insurance-prices/'   

dog_insurance <- url %>%
  xml2::read_html() %>%
  html_nodes(xpath='//*[@id="post-1016"]/div/table') %>%
  html_table()

dog_insurance <- dog_insurance[[1]]

head(dog_insurance)

saveRDS(dog_insurance, "data/costs/raw/dog_insurance.Rds") # extracted on the 30 March 2020
```

```{r}
dog_insurance <- readRDS("data/costs/raw/dog_insurance.Rds") %>% 
  as_tibble() %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>% 
  # select(-) %>% 
  mutate(average_accident_policy_cost_annual = 
           gsub(",", "",
                average_accident_policy_cost_annual, 
                fixed = TRUE),
         average_illness_policy_cost_annual = 
           gsub(",", "",
                average_illness_policy_cost_annual, 
                fixed = TRUE),
         average_comprehensive_policy_cost_annual = 
           gsub(",", "",
                average_comprehensive_policy_cost_annual, 
                fixed = TRUE)
  ) %>% 
  mutate(average_accident_policy_cost_annual = 
           as.numeric(gsub("$", "",
                           average_accident_policy_cost_annual, 
                           fixed = TRUE)),
         average_illness_policy_cost_annual = 
           as.numeric(gsub("$", "",
                           average_illness_policy_cost_annual, 
                           fixed = TRUE)),
         average_comprehensive_policy_cost_annual = 
           as.numeric(gsub("$", "",
                           average_comprehensive_policy_cost_annual, 
                           fixed = TRUE))
  )

saveRDS(dog_insurance, "data/costs/clean/dog_insurance.Rds") # extracted on the 30 March 2020
```

```{r}
dog_insurance <- readRDS("data/costs/clean/dog_insurance.Rds")

glimpse(dog_insurance)
```

```{r}
frq(dog_insurance, cost_compared_to_other_breeds)
```